### ISSUE TITLE
feature request: promptLabel should allow jsx value

### ISSUE THREAD

**Issue by gaoryrt** [linuswillner/react-console-emulator#210]
```
  promptLabel={() => {
    return <div className="line">
      <span className="black _red">
        {dayjs().format('HH:mm:ss')}
      </span>
	  <span>$</span>
    </div>
  }}
```
so the prompt label could change dynamicly.

**Comment by gaoryrt** [comment]
btw, this repo deserves more stars, shout out to the owner

**Comment by linuswillner** [comment]
Excellent idea, and something I totally didn’t think of! I’ll look into this ASAP.

**Comment by linuswillner** [comment]
This issue has been sitting for a year, give or take, but I finally got around to implementing this now! Sorry for the long wait on this one, it's coming very soon 😃

**Comment by gaoryrt** [comment]
Glad to hear that! Much appreciate!
