### ISSUE TITLE
Ability to change/update history item

### ISSUE THREAD

**Issue by jay-jlm** [linuswillner/react-console-emulator#638]
I was searching the API for some method like `updateHistoryAtIndex(index, updatedString)` but could not find one.
This would be super useful  for things like counters, progress indicators and such.

Let me know if there is some workaround/hack in order to accomplish this.

**Comment by linuswillner** [comment]
I don't think allowing the updating of history items would in itself be anything more than a hack, ironically enough. I can see what you're looking for with this idea though, and I'll absolutely consider implementing it somehow. However, presently, there is no way to accomplish this.

**Comment by linuswillner** [comment]
Implemented in 223f01212748c4a5049c73e424f5b14d6062e5d9. Will be pushed with the next major version.
