### ISSUE TITLE
Ability to mimic a read-only state

### ISSUE THREAD

**Issue by jay-jlm** [linuswillner/react-console-emulator#639]
Currently setting the `disabled` property to `true` does not hide the prompt label, which makes sense from a semantic perspective.

Looks like that as it is today, to fully mimic a read-only state I both have to set `disabled` property to true as well as set the `promptLabel` to a non-empty whitespace string.

Maybe having either a `readOnly` property (controlled approach) or `hidePromptWhenDisabled` property ("set and forget" approach) would be a good middle ground between keeping a more granular  and semantic API but also not forcing the user to keep tabs on the label prompt value so much.

Curious on your thoughts on the matter.

**Comment by linuswillner** [comment]
I presume this is partially related to your feature request in #638. You've absolutely got a good idea here, and I'll definitely implement something like this in conjunction with your other idea.

**Comment by linuswillner** [comment]
Implemented in 914231a. Will be pushed out with the next version.
