### ISSUE TITLE
Prompt/input styling is only applied to the latest prompt/input

### ISSUE THREAD

**Issue by jay-jlm** [linuswillner/react-console-emulator#640]
Looks like evrything that is considered "history" is assigned an uniform css style, and only the latest/active prompt label and input text have a distinct styling applied to them, however that is not how it works on most  real-life terminals and it kind of breaks the "illusion" of being on an actual terminal quite a lot, imho.
It would be nice to know if this happens to be a known limitation and something that is on your radar as a possible point for enhancement.

**Comment by linuswillner** [comment]
This design choice was subjectively motivated, seeing as in those terminals colouring was not preserved on return. However, now that you point it out, adding the ability to retain prompt styling is a fairly trivial enhancement that I should absolutely add.

**Comment by linuswillner** [comment]
Implemented in c234ec8. Will be pushed out with the next version.
