### ISSUE TITLE
passThroughCommand like prop

### ISSUE THREAD

**Issue by scovic** [linuswillner/react-console-emulator#672]
Is there a prop that I can use to handle my input (command), so I can take the input, send it over network (http, ws, ...) and then print the result I get, without checking if the input is part of commands prop, so i don't get `Command 'my-command' not found!` ?

**Comment by linuswillner** [comment]
As far as I can see, you're looking for a method to take input, run an async task, and then push the result to the terminal separately? Could [Async output](https://github.com/linuswillner/react-console-emulator/blob/master/docs/API.md#async-output) be what you're looking for?

**Comment by scovic** [comment]
Yes, but i don't want to define a command for it in **commands** prop, i want to take whole raw input and send it over the network.

**Comment by linuswillner** [comment]
Ah, so you're looking for something akin to what was suggested in #415, and just pass all of it through. Unfortunately, I have in the past declined to add this feature for a multitude of reasons, not least of which being the ones outlined in https://github.com/linuswillner/react-console-emulator/issues/415#issuecomment-634048715. That feature is still unviable for me to dedicate lots of time and effort to (The former of which I don't have a whole lot) when actual quality-of-life improvements are still on the docket.

I might implement something like this one day, but for now, I can't promise anything. If you absolutely need to pass the input over the network sight unseen, then your best option is probably to look for a terminal library with a lesser focus on a ready-made command API.
