### ISSUE TITLE
"ReactHotLoader" occurrences in published package

### ISSUE THREAD

**Issue by Sebobo** [linuswillner/react-console-emulator#846]
At the end of each file in the package version from npm a larger definition regarding the `ReactHotLoader` is contained.
When I include this package I have 20 instances of that including the path `C:\Users\LWTech Gaming\Code Projects\react-console-emulator\src` in my bundle.

Probably this is a configuration error in webpack step?

**Comment by linuswillner** [comment]
Whoops, this does indeed appear to be an error, as that should not be going downstream. I'll look into fixing this ASAP - if you know the fix and want to hurry it along, do by all means share!

**Comment by Sebobo** [comment]
Thx for looking into it!

For now I patched it out which saved 10KB in the minified bundle ;)

I had a look at the config before I opened the issue, but I couldn't directly see what's wrong as I didn't fully understand the publishing workflow.
You already have the HotLoader only in the Production plugins, so I would have assumed that should work properly.

**Comment by linuswillner** [comment]
Fixed in v5.0.1. Thanks for flagging!

**Comment by Sebobo** [comment]
Thx, perfect!

**Comment by Sebobo** [comment]
Btw. using the plugin for https://github.com/Sebobo/Shel.Neos.Terminal. Works really well :)

**Comment by linuswillner** [comment]
Wow, this looks super awesome! Thanks for using my little tool for this! 😊
