### ISSUE TITLE
[object Object] when dangerMode={true}

### ISSUE THREAD

**Issue by paulatwilson** [linuswillner/react-console-emulator#860]
Hi there,

When I set dangerMode={true} with every command I always get:`[object Object]` echoed back before my content is displayed.
```
        <Terminal
          dangerMode
          style={termStyle}
          commands={commands}
          welcomeMessage="HISAC Emergency Terminal. Authorised access only!"
          promptLabel={promptLabel}
          autoFocus
          ref={ref}
          noAutoScroll
        />
```

when any of my commands the [object] [Object] comes up:

```
[object Object]
Processing...
PRE: DIR: ARCHIVES
PRE: RES: INTENRAL
POS: DIC: INTERFACES
CON: DIC: EXTERNAL
PRE: DIR: CLASSIFIED
```

It appears to be replacing the "prompt" and the "command" with `[object] [Object]`

```
$/ ls
```

when I press enter, it gets replaced with:

```
[object] [Object]
```

**Comment by linuswillner** [comment]
Could you show me what your command logic looks like?

**Comment by phpzzer** [comment]
may be you trying to do somehitng like :
`return terminal.pushToStdout({})`
try to use 
` return terminal.pushToStdout("string here")`

for example

**Comment by Sebobo** [comment]
I have the same issue with `dangerMode`. 

I would assume it's because `constructEcho` doesn't return a raw string in  https://github.com/linuswillner/react-console-emulator/blob/6db3cc0d3efd28e7656d59491d4fa41598743850/src/utils/constructEcho.js#L65

**Comment by linuswillner** [comment]
Alright, so, I finally have time to look into this now. I've seen enough forks that fix this issue to the point that I now know where it's coming from. I'll fix it ASAP.

**Comment by asheeeshh** [comment]
still not fixed?

**Comment by leo-castro** [comment]
bump

**Comment by linuswillner** [comment]
Hi all, sorry for the terribly long wait, life's been way too busy for me to work on a library I first wrote when I was 17 years old, lol. But I am pleased to announce I'm going to fix this bug right now! (Better late than never, I hope)
